### ISSUE TITLE
News Plugin Problem

### ISSUE THREAD

**Issue by hagerp** [in2code-de/ipandlanguageredirect#23]
Hi the Detail Page of the News Plugin always makes an redirect to a page that does not exist.
I tried to exclude it with

 'pidInRootline' => [
                '49',
                '51'
            ],

But it doesnt effect it.
any suggestions?
thanks

**Comment by sbusemann** [comment]
This ticket is pretty old. If you still need support, you can use: https://www.in2code.de/agentur/typo3-extensions/early-access-programm#c4288
