### ISSUE TITLE
TYPO3 V12 compatibility

### ISSUE THREAD

**Issue by mschwemer** [in2code-de/ipandlanguageredirect#38]
There will be an EXT:ipandlanguageredirect version, which is compatible with TYPO3 core V12. It is currently under development and testing.

If you need early access to this version, please head over to https://www.in2code.de/agentur/typo3-extensions/early-access-programm/ and support our work.

**Comment by sbusemann** [comment]
released

**Comment by Patta** [comment]
@sbusemann the version requirements for typo3-core are different in ext_emconf.php and composer.json. This should imho be a major 6.0.0 release with typo3 v12 as a new dependency.

**Comment by sbusemann** [comment]
@Patta thx for the hint - it is fixed with 5.2.1
